server:
  port: 8000
spring:
  datasource:
    url: jdbc:mysql:///cloud?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.25.80:8848
  application:
    name: user-service
dubbo:
  scan:
    base-packages: com.hs.userservice.service
  protocol:
    name: dubbo
    port: -1
  cloud:
    subscribed-services: *
